apiVersion: v1
kind: Service
metadata:
  name: netty-to-log-service
spec:
  selector:
    camel.apache.org/integration: netty-to-log-8293
  ports:
    - protocol: TCP
      port: 8293
      targetPort: 8293
      nodePort: 30293
  type: NodePort
