apiVersion: v1
kind: Service
metadata:
  name: netty-to-rabbit-service
spec:
  selector:
    camel.apache.org/integration: netty-to-rabbit-pipe
  ports:
    - protocol: TCP
      port: 8294
      targetPort: 8294
      nodePort: 30294
  type: LoadBalancer
