apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: cxf-source
spec:
  definition:
    title: "CXF SOAP"
    description: Handle SOAP Requests
    properties:
      url:
        title: URL
        description: Url service 
        type: string
        example: "http://0.0.0.0:8080/soap"
  dependencies:
  - "camel:core"
  - "camel:kamelet"
  - "camel:cxf-soap"
  - "mvn:org.ow2.asm:asm:9.2"  # Adding ASM dependency
  - "github:williamdlm/testing_jitpack/42baadcf9a"
  template:
    from:
      uri: "cxf:{{url}}?serviceClass=com.github.williamdlm.service.IntroduceImpl"
      steps:
      - to: kamelet:sink
