apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: cxf-bean-source
spec:
  definition:
    title: "CXF SOAP"
    description: Handle SOAP Requests
    properties:
      url:
        title: URL
        description: Url service 
        type: string
        example: "/soap"
  dependencies:
  - "camel:core"
  - "camel:kamelet"
  - "camel:cxf-soap"
  - "mvn:org.ow2.asm:asm:9.2"  # Adding ASM dependency
  - "github:williamdlm/testing_jitpack/0cb527bc9f"
  template:
    beans:
      - name: introduceEndpoint
        method: introduceEndpoint
        type: >-
          #class:com.github.williamdlm.config.CxfConfig
    from:
      uri: "cxf:bean:introduceEndpoint"
      steps:
      - to: kamelet:sink
