apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: cxf-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: cxf-source
    properties:
      url: "/soap"  # nodeIp:port/services/soap
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
