apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: cxf-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: cxf-source
    properties:
      url: "http://0.0.0.0:8080/soap"  
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
