apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: timer-to-cxfsink
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      period: 10000  
      message: "olá mundo"  # Definindo a mensagem a ser enviada
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: cxf-bean-sink